# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='bus',
        ),
        migrations.AddField(
            model_name='location',
            name='bus_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='nfc_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
