# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170604_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='tag_id',
            new_name='ID',
        ),
    ]
