# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20170627_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ID',
            new_name='bus',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
    ]
